apiVersion: techzone.ibm.com/v1alpha1
kind: Component
metadata:
  name: mq
  description: IBM MQ
  namespace: cpi
  tags:
    - mq
    - cloud-pak-for-integration
spec:
  type: application
  lifecycle: production
  owner: group:integration-team
