apiVersion: techzone.ibm.com/v1alpha1
kind: Component
metadata:
  name: app-connect
  description: App Connect
  namespace: cpi
  tags:
    - appconnect
    - cloud-pak-for-integration
spec:
  type: application
  lifecycle: production
  owner: group:integration-team
  subcomponentOf: component:cloud-pak/cloud-pak-for-integration-2022.2
